### ISSUE TITLE
Does not obtain full screen size on OSX

### ISSUE THREAD

**Issue by zunda** [zunda/rabbit#1]
https://github.com/rabbit-shocker/rabbit/issues/81 のための作業中のメモ

66ae3520d44a1630e340ffe9cab19daad539b8a3 をOSXで起動すると、下記のような感じの出力が得られる

```
[800, 600]
:configured
[0, 45, 800, 600]
:configured
[0, 45, 800, 600]
:configured
[0, 0, 1440, 900]
:fullscreened
["/usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 151, :set_draw, 800, 600]
[800, 600]
["/usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 178, :set_configure_event_after, 1440, 900]
["/usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 151, :set_draw, 1440, 900]
["/usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 151, :set_draw, 1440, 900]
```

**Comment by zunda** [comment]
Ubuntu 15.10の場合

```
[800, 600]
:fullscreened
:configured
[0, 0, 800, 600]
:configured
[477, 197, 800, 600]
:configured
[0, 0, 1280, 800]
:configured
[0, 0, 1280, 800]
:configured
[0, 0, 1280, 800]
["/home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 178, :set_configure_event_after, 1280, 800]
["/home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 151, :set_draw, 1280, 800]
[1280, 800]
["/home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb", 151, :set_draw, 1280, 800]
```

**Comment by zunda** [comment]
lib/rabbit/renderer/display/base.rbの`configure_event`コールバックの`event`にはどちらも同様にフルスクリーンの解像度が知らされている。フルスクリーンになったあとにlib/rabbit/renderer/display/base.rbの`refresh_size`メソッドが呼ばれるようだが、`@drawable`の`width`と`height`はOSXの場合は変化していない。

**Comment by zunda** [comment]
64e210f2f69783af3fa60826a0ba43abd7af5929 でOSXでも期待どおりフルスクリーン表示されるようになった(が`refresh_size`がどんどーん呼ばれているのが見える)。どこかで`@size_dirty`を`true`にしなきゃいけないのかな？

**Comment by zunda** [comment]
https://github.com/zunda/rabbit/commit/e56ca55d07277e834ace44e33b744ae4acfebf9b でどのようなコールバックが呼ばれているか確認したところ、`configure_event`にフルスクリーンの解像度が渡ってきている場合があった。`@size_dirty = true`になるはずなので`refresh_size`内で解像度の変更が反映されるはずなのに、そうなっていない。

```
  :
signal_connect: size_prepared /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/image-data-loader.rb
signal_connect: size_prepared /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/image-data-loader.rb
signal_connect: configure_event 800 600 /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
signal_connect: window_state_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/frame.rb
signal_connect: window_state_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
signal_connect: configure_event 800 600 /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
signal_connect: configure_event 1440 900 /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
signal_connect: window_state_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/frame.rb
signal_connect: expose_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
signal_connect_after: configure_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
signal_connect: expose_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
[:refresh_size, 1440, 900]
[WARNING]
RuntimeError:
/usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:180:in `refresh_size'
  :
```

**Comment by zunda** [comment]
332fba217440d438d46fcf0458cf4344128fd282 によるとサイズの変更を受け取ってるのは`Rabbit::Renderer::Display::DrawingArea`のようだ

```
  :
configured: 0 45 800 600
signal_connect: configure_event Rabbit::Renderer::Display::DrawingArea 1440 900 /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
Tracing @size_dirty
configured: 0 0 1440 900
signal_connect: window_state_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/frame.rb
signal_connect: expose_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
signal_connect_after: configure_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
signal_connect: expose_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
[:refresh_size, Rabbit::Renderer::Display::DrawingArea, 1440, 900]
  :
```

**Comment by zunda** [comment]
`trace_var`はインスタンス変数の変更は検出してくれないようだ

**Comment by zunda** [comment]
「gdbでb rb_ivar_set」https://twitter.com/n0kada/status/683837030963359745 あざす！OSXでどうしよう

**Comment by zunda** [comment]
b5730c87cbb750553f763bad00a28deef6d683cd で `@size_dirty` を `false` にしてる場所が見えたかもしれない

```
configured: 0 0 1440 900
@size_dirty is set true for Rabbit::Renderer::Display::DrawingArea at /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:200:in `configured' called from /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/progress.rb:50:in `configured'
signal_connect: window_state_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/frame.rb
signal_connect: expose_event /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
@size_dirty is set false for Rabbit::Renderer::Display::DrawingArea at /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:186:in `refresh_size' called from /usr/local/lib/ruby/gems/2.2.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:23:in `width'
```

**Comment by zunda** [comment]
あれれ期待されてる動作だ

**Comment by zunda** [comment]
Ubuntu 15.10上でもそれほど違いはない

```
configured: 477 197 800 600
@size_dirty is set true for Rabbit::Renderer::Display::DrawingArea at /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:200:in `configured' called from /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/progress.rb:50:in `configured'
signal_connect: configure_event Rabbit::Renderer::Display::DrawingArea 1280 800 /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
configured: 0 0 1280 800
@size_dirty is set true for Rabbit::Renderer::Display::DrawingArea at /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:200:in `configured' called from /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/progress.rb:50:in `configured'
signal_connect: configure_event Rabbit::Renderer::Display::DrawingArea 1280 800 /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
configured: 0 0 1280 800
@size_dirty is set true for Rabbit::Renderer::Display::DrawingArea at /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:200:in `configured' called from /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/progress.rb:50:in `configured'
signal_connect: configure_event Rabbit::Renderer::Display::DrawingArea 1280 800 /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb
configured: 0 0 1280 800
@size_dirty is set true for Rabbit::Renderer::Display::DrawingArea at /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:200:in `configured' called from /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/progress.rb:50:in `configured'
signal_connect_after: configure_event /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
signal_connect: expose_event /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/drawing-area-primitive.rb
@size_dirty is set false for Rabbit::Renderer::Display::DrawingArea at /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:186:in `refresh_size' called from /home/zunda/.gem/ruby/2.1.0/gems/rabbit-2.1.9/lib/rabbit/renderer/display/base.rb:23:in `width'
```
